variables:
    GIT_SUBMODULE_STRATEGY: recursive

compile_pdf:
    image:
        name: texlive/texlive
        entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
    script:
        - apt-get update
        - apt-get install qpdf -y
        - apt-get -y upgrade
        - apt-get -y autoclean
        - apt-get -y autoremove
        - latexmk -pdf paper.tex
        - qpdf --linearize paper.pdf paper.lin.pdf
    artifacts:
        paths:
        - paper.pdf
        - paper.lin.pdf
